using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GoPOS.Models
{
    public class SALE_M
    {
        /// <summary>
        /// 매출TR-HEADER

        /// </summary>
        public SALE_M()
        {
            /*            
            SHOP_CODE                VARCHAR(6) NOT NULL,
            SALE_DATE                VARCHAR(8) NOT NULL,
            POS_NO                   VARCHAR(2) NOT NULL,
            BILL_NO                  VARCHAR(4) NOT NULL,
            REGI_SEQ                 VARCHAR(2) DEFAULT '01' NOT NULL,
            SALE_YN                  VARCHAR(1) DEFAULT 'Y' NOT NULL,
            TOT_SALE_AMT             NUMERIC(12,2) DEFAULT 0 NOT NULL,
            TOT_DC_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            SVC_TIP_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL,
            TOT_ETC_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DCM_SALE_AMT             NUMERIC(12,2) DEFAULT 0 NOT NULL,
            VAT_SALE_AMT             NUMERIC(12,2) DEFAULT 0 NOT NULL,
            VAT_AMT                  NUMERIC(12,2) DEFAULT 0 NOT NULL,
            NO_VAT_SALE_AMT          NUMERIC(12,2) DEFAULT 0 NOT NULL,
            NO_TAX_SALE_AMT          NUMERIC(12,2) DEFAULT 0 NOT NULL,
            EXP_PAY_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL,
            GST_PAY_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL,
            RET_PAY_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL,
            CASH_AMT                 NUMERIC(12,2) DEFAULT 0 NOT NULL,
            CRD_CARD_AMT             NUMERIC(12,2) DEFAULT 0 NOT NULL,
            WES_AMT                  NUMERIC(12,2) DEFAULT 0 NOT NULL,
            TK_GFT_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            TK_FOD_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            CST_POINT_AMT            NUMERIC(12,2) DEFAULT 0 NOT NULL,
            JCD_CARD_AMT             NUMERIC(12,2) DEFAULT 0 NOT NULL,
            RFC_AMT                  NUMERIC(12,2) DEFAULT 0 NOT NULL,
            CST_NO                   VARCHAR(10),
            CST_CARD_NO              VARCHAR(40),
            CST_SALE_POINT           NUMERIC(9,0) DEFAULT 0 NOT NULL,
            DC_GEN_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DC_SVC_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DC_PCD_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DC_CPN_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DC_CST_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DC_TFD_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DC_PRM_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DC_CRD_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DC_PACK_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DC_LYT_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            REPAY_CASH_AMT           NUMERIC(12,2) DEFAULT 0 NOT NULL,
            REPAY_TK_GFT_AMT         NUMERIC(12,2) DEFAULT 0 NOT NULL,
            CASH_BILL_AMT            NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DLV_ORDER_FLAG           VARCHAR(1) DEFAULT '0' NOT NULL,
            FD_TBL_CODE              VARCHAR(3) DEFAULT '000' NOT NULL,
            FD_GST_CNT_T             NUMERIC(5,0) DEFAULT 0 NOT NULL,
            FD_GST_CNT_1             NUMERIC(4,0) DEFAULT 0 NOT NULL,
            FD_GST_CNT_2             NUMERIC(4,0) DEFAULT 0 NOT NULL,
            FD_GST_CNT_3             NUMERIC(4,0) DEFAULT 0 NOT NULL,
            FD_GST_CNT_4             NUMERIC(4,0) DEFAULT 0 NOT NULL,
            ORG_BILL_NO              VARCHAR(20),
            ORDER_NO                 VARCHAR(4),
            INSERT_DT                VARCHAR(14) NOT NULL,
            EMP_NO                   VARCHAR(4) NOT NULL,
            SEND_FLAG                VARCHAR(1) DEFAULT '0' NOT NULL,
            SEND_DT                  VARCHAR(14),
            PAY_OUT_DT               VARCHAR(14),
            CST_NAME                 VARCHAR(24),
            DLV_EMP_NO               VARCHAR(4),
            DLV_START_DT             VARCHAR(14),
            DLV_PAYIN_EMP_NO         VARCHAR(4),
            DLV_PAYIN_DT             VARCHAR(14),
            NEW_DLV_ADDR_YN          VARCHAR(1) DEFAULT 'N' NOT NULL,
            DLV_ADDR                 VARCHAR(80),
            DLV_ADDR_DTL             VARCHAR(88),
            NEW_DLV_TEL_NO_YN        VARCHAR(1) DEFAULT 'N' NOT NULL,
            DLV_TEL_NO               VARCHAR(24),
            DLV_CL_CODE              VARCHAR(3),
            DLV_CM_CODE              VARCHAR(5),
            TRAVEL_CODE              VARCHAR(6),
            RSV_NO                   VARCHAR(10),
            PRE_PAY_CASH             NUMERIC(12,2),
            PRE_PAY_CARD             NUMERIC(12,2),
            RSV_USER_NAME            VARCHAR(40),
            RSV_USER_TEL_NO          VARCHAR(24),
            CST_AVL_POINT            NUMERIC(9,0),
            AFFILIATE_CODE           VARCHAR(6),
            LOCAL_POINT_YN           VARCHAR(1),
            MCP_AMT                  NUMERIC(12,2),
            PCD_CARD_AMT             NUMERIC(12,2),
            CST_ANN_POINT            NUMERIC(9,0) DEFAULT 0 NOT NULL,
            CST_NEW_POINT            NUMERIC(9,0) DEFAULT 0 NOT NULL,
            CST_USE_POINT            NUMERIC(9,0) DEFAULT 0 NOT NULL,
            CST_DATA                 VARCHAR(4096),
            DLV_BOWLIN_YN            VARCHAR(1) DEFAULT 'N' NOT NULL,
            DLV_BOWLIN_EMP_NO        VARCHAR(4),
            DLV_BOWLIN_DT            VARCHAR(14),
            FD_GST_FLAG_YN           VARCHAR(1),
            FD_GST_FLAG_1            VARCHAR(2),
            FD_GST_FLAG_2            VARCHAR(2),
            SALE_CHG_FLAG            VARCHAR(1) DEFAULT '0' NOT NULL,
            PPC_CARD_AMT             NUMERIC(12,2) DEFAULT 0,
            EGIFT_AMT                NUMERIC(12,2) DEFAULT 0,
            MOBILE_ORDER_FLAG        VARCHAR(2) DEFAULT '00',
            MOBILE_ORDER_NO          VARCHAR(20) DEFAULT '',
            RFND_TYPE_CODE           VARCHAR(1),
            TAX_RFND_AMT             NUMERIC(12,2) DEFAULT 0 NOT NULL,
            TAX_RFND_FEE             NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DC_TAX_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DUTCH_ORDER_NO           VARCHAR(4) DEFAULT '',
            O2O_AMT                  NUMERIC(12,2) DEFAULT 0 NOT NULL,
            DLV_SAFE_TEL_NO          VARCHAR(15),
            DLV_EXPIRE_TIME          VARCHAR(14),
            EXTERN_GUEST_FLAG        VARCHAR(1) DEFAULT '0',
            DCC_EX_RATE_CODE         VARCHAR(1),
            DCC_RCV_TEXT             VARCHAR(100),
            SP_PAY_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
            HOOK_ORDER_CHANNEL_TYPE  VARCHAR(30) DEFAULT '',
            DEPOSIT_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL
            */      
        }

        public SALE_M(string shop_code, string sale_date, string pos_no, string bill_no)
        {
            this.SHOP_CODE = shop_code;
            this.SALE_DATE = sale_date;
            this.POS_NO = pos_no;
            this.BILL_NO = bill_no;         
        }

        public string SHOP_CODE { get; set; } = string.Empty;            //SHOP_CODE                VARCHAR(6) NOT NULL,
        public string SALE_DATE { get; set; } = string.Empty;            //SALE_DATE                VARCHAR(8) NOT NULL,
        public string POS_NO { get; set; } = string.Empty;               //POS_NO                   VARCHAR(2) NOT NULL,
        public string BILL_NO { get; set; } = string.Empty;              //BILL_NO                  VARCHAR(4) NOT NULL,
        public string REGI_SEQ { get; set; } = "01";             //REGI_SEQ                 VARCHAR(2) DEFAULT '01' NOT NULL,
        public string SALE_YN { get; set; } = "Y";              //SALE_YN                  VARCHAR(1) DEFAULT 'Y' NOT NULL,
        public string TOT_SALE_AMT { get; set; } = "0";         //TOT_SALE_AMT             NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string TOT_DC_AMT { get; set; } = "0";           //TOT_DC_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string SVC_TIP_AMT { get; set; } = "0";          //SVC_TIP_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string TOT_ETC_AMT { get; set; } = "0";          //TOT_ETC_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DCM_SALE_AMT { get; set; } = "0";         //DCM_SALE_AMT             NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string VAT_SALE_AMT { get; set; } = "0";         //VAT_SALE_AMT             NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string VAT_AMT { get; set; } = "0";              //VAT_AMT                  NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string NO_VAT_SALE_AMT { get; set; } = "0";      //NO_VAT_SALE_AMT          NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string NO_TAX_SALE_AMT { get; set; } = "0";      //NO_TAX_SALE_AMT          NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string EXP_PAY_AMT { get; set; } = "0";          //EXP_PAY_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string GST_PAY_AMT { get; set; } = "0";          //GST_PAY_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string RET_PAY_AMT { get; set; } = "0";          //RET_PAY_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string CASH_AMT { get; set; } = "0";             //CASH_AMT                 NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string CRD_CARD_AMT { get; set; } = "0";         //CRD_CARD_AMT             NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string WES_AMT { get; set; } = "0";              //WES_AMT                  NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string TK_GFT_AMT { get; set; } = "0";           //TK_GFT_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string TK_FOD_AMT { get; set; } = "0";           //TK_FOD_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string CST_POINT_AMT { get; set; } = "0";        //CST_POINT_AMT            NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string JCD_CARD_AMT { get; set; } = "0";         //JCD_CARD_AMT             NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string RFC_AMT { get; set; } = "0";              //RFC_AMT                  NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string CST_NO { get; set; } = string.Empty;               //CST_NO                   VARCHAR(10),
        public string CST_CARD_NO { get; set; } = string.Empty;          //CST_CARD_NO              VARCHAR(40),
        public string CST_SALE_POINT { get; set; } = "0";       //CST_SALE_POINT           NUMERIC(9,0) DEFAULT 0 NOT NULL,
        public string DC_GEN_AMT { get; set; } = "0";           //DC_GEN_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DC_SVC_AMT { get; set; } = "0";           //DC_SVC_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DC_PCD_AMT { get; set; } = "0";           //DC_PCD_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DC_CPN_AMT { get; set; } = "0";           //DC_CPN_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DC_CST_AMT { get; set; } = "0";           //DC_CST_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DC_TFD_AMT { get; set; } = "0";           //DC_TFD_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DC_PRM_AMT { get; set; } = "0";           //DC_PRM_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DC_CRD_AMT { get; set; } = "0";           //DC_CRD_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DC_PACK_AMT { get; set; } = "0";          //DC_PACK_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DC_LYT_AMT { get; set; } = "0";           //DC_LYT_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string REPAY_CASH_AMT { get; set; } = "0";       //REPAY_CASH_AMT           NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string REPAY_TK_GFT_AMT { get; set; } = "0";     //REPAY_TK_GFT_AMT         NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string CASH_BILL_AMT { get; set; } = "0";        //CASH_BILL_AMT            NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DLV_ORDER_FLAG { get; set; } = "0";       //DLV_ORDER_FLAG           VARCHAR(1) DEFAULT '0' NOT NULL,
        public string FD_TBL_CODE { get; set; } = "000";          //FD_TBL_CODE              VARCHAR(3) DEFAULT '000' NOT NULL
        public string FD_GST_CNT_T { get; set; } = "0";         //FD_GST_CNT_T             NUMERIC(5,0) DEFAULT 0 NOT NULL,
        public string FD_GST_CNT_1 { get; set; } = "0";         //FD_GST_CNT_1             NUMERIC(4,0) DEFAULT 0 NOT NULL,
        public string FD_GST_CNT_2 { get; set; } = "0";         //FD_GST_CNT_2             NUMERIC(4,0) DEFAULT 0 NOT NULL,
        public string FD_GST_CNT_3 { get; set; } = "0";         //FD_GST_CNT_3             NUMERIC(4,0) DEFAULT 0 NOT NULL,
        public string FD_GST_CNT_4 { get; set; } = "0";         //FD_GST_CNT_4             NUMERIC(4,0) DEFAULT 0 NOT NULL,
        public string ORG_BILL_NO { get; set; } = string.Empty;          //ORG_BILL_NO              VARCHAR(20),
        public string ORDER_NO { get; set; } = string.Empty;             //ORDER_NO                 VARCHAR(4),
        public string INSERT_DT { get; set; } = "";            //INSERT_DT                VARCHAR(14) NOT NULL,
        public string EMP_NO { get; set; } = "0000"; // 받아서처리               //EMP_NO                   VARCHAR(4) NOT NULL,
        public string SEND_FLAG { get; set; } = "0";            //SEND_FLAG                VARCHAR(1) DEFAULT '0' NOT NULL,
        public string SEND_DT { get; set; } = string.Empty;              //SEND_DT                  VARCHAR(14),
        public string PAY_OUT_DT { get; set; } = string.Empty;           //PAY_OUT_DT               VARCHAR(14),
        public string CST_NAME { get; set; } = string.Empty;             //CST_NAME                 VARCHAR(24),
        public string DLV_EMP_NO { get; set; } = string.Empty;           //DLV_EMP_NO               VARCHAR(4),
        public string DLV_START_DT { get; set; } = string.Empty;         //DLV_START_DT             VARCHAR(14),
        public string DLV_PAYIN_EMP_NO { get; set; } = string.Empty;     //DLV_PAYIN_EMP_NO         VARCHAR(4),
        public string DLV_PAYIN_DT { get; set; } = string.Empty;         //DLV_PAYIN_DT             VARCHAR(14),
        public string NEW_DLV_ADDR_YN { get; set; } = "N";      //NEW_DLV_ADDR_YN          VARCHAR(1) DEFAULT 'N' NOT NULL,
        public string DLV_ADDR { get; set; } = string.Empty;             //DLV_ADDR                 VARCHAR(80),
        public string DLV_ADDR_DTL { get; set; } = string.Empty;         //DLV_ADDR_DTL             VARCHAR(88),
        public string NEW_DLV_TEL_NO_YN { get; set; } = "N";    //NEW_DLV_TEL_NO_YN        VARCHAR(1) DEFAULT 'N' NOT NULL,
        public string DLV_TEL_NO { get; set; } = string.Empty;           //DLV_TEL_NO               VARCHAR(24),
        public string DLV_CL_CODE { get; set; } = string.Empty;          //DLV_CL_CODE              VARCHAR(3),
        public string DLV_CM_CODE { get; set; } = string.Empty;          //DLV_CM_CODE              VARCHAR(5),
        public string TRAVEL_CODE { get; set; } = string.Empty;          //TRAVEL_CODE              VARCHAR(6),
        public string RSV_NO { get; set; } = string.Empty;               //RSV_NO                   VARCHAR(10),
        public string PRE_PAY_CASH { get; set; } = "0";         //PRE_PAY_CASH             NUMERIC(12,2),
        public string PRE_PAY_CARD { get; set; } = "0";         //PRE_PAY_CARD             NUMERIC(12,2),
        public string RSV_USER_NAME { get; set; } = string.Empty;        //RSV_USER_NAME            VARCHAR(40),
        public string RSV_USER_TEL_NO { get; set; } = string.Empty;      //RSV_USER_TEL_NO          VARCHAR(24),
        public string CST_AVL_POINT { get; set; } = "0";        //CST_AVL_POINT            NUMERIC(9,0),
        public string AFFILIATE_CODE { get; set; } = string.Empty;       //AFFILIATE_CODE           VARCHAR(6),
        public string LOCAL_POINT_YN { get; set; } = string.Empty;       //LOCAL_POINT_YN           VARCHAR(1),
        public string MCP_AMT { get; set; } = "0";              //MCP_AMT                  NUMERIC(12,2),
        public string PCD_CARD_AMT { get; set; } = "0";         //PCD_CARD_AMT             NUMERIC(12,2),
        public string CST_ANN_POINT { get; set; } = "0";        //CST_ANN_POINT            NUMERIC(9,0) DEFAULT 0 NOT NULL,
        public string CST_NEW_POINT { get; set; } = "0";        //CST_NEW_POINT            NUMERIC(9,0) DEFAULT 0 NOT NULL,
        public string CST_USE_POINT { get; set; } = "0";        //CST_USE_POINT            NUMERIC(9,0) DEFAULT 0 NOT NULL,
        public string CST_DATA { get; set; } = string.Empty;             //CST_DATA                 VARCHAR(4096),
        public string DLV_BOWLIN_YN { get; set; } = "N";        //DLV_BOWLIN_YN            VARCHAR(1) DEFAULT 'N' NOT NULL,
        public string DLV_BOWLIN_EMP_NO { get; set; } = string.Empty;    //DLV_BOWLIN_EMP_NO        VARCHAR(4),
        public string DLV_BOWLIN_DT { get; set; } = string.Empty;        //DLV_BOWLIN_DT            VARCHAR(14),
        public string FD_GST_FLAG_YN { get; set; } = string.Empty;       //FD_GST_FLAG_YN           VARCHAR(1),
        public string FD_GST_FLAG_1 { get; set; } = string.Empty;        //FD_GST_FLAG_1            VARCHAR(2),
        public string FD_GST_FLAG_2 { get; set; } = string.Empty;        //FD_GST_FLAG_2            VARCHAR(2),
        public string SALE_CHG_FLAG { get; set; } = "0";        //SALE_CHG_FLAG            VARCHAR(1) DEFAULT '0' NOT NULL,
        public string PPC_CARD_AMT { get; set; } = "0";         //PPC_CARD_AMT             NUMERIC(12,2) DEFAULT 0,
        public string EGIFT_AMT { get; set; } = "0";            //EGIFT_AMT                NUMERIC(12,2) DEFAULT 0,
        public string MOBILE_ORDER_FLAG { get; set; } = "0";    //MOBILE_ORDER_FLAG        VARCHAR(2) DEFAULT '00',
        public string MOBILE_ORDER_NO { get; set; } = "";      //MOBILE_ORDER_NO          VARCHAR(20) DEFAULT '',
        public string RFND_TYPE_CODE { get; set; } = string.Empty;       //RFND_TYPE_CODE           VARCHAR(1),
        public string TAX_RFND_AMT { get; set; } = "0";         //TAX_RFND_AMT             NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string TAX_RFND_FEE { get; set; } = "0";         //TAX_RFND_FEE             NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DC_TAX_AMT { get; set; } = "0";           //DC_TAX_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DC_YAP_AMT { get; set; } = "0";               
        public string DUTCH_ORDER_NO { get; set; } = string.Empty;              
        public string O2O_AMT { get; set; } = "0";                    //O2O_AMT                  NUMERIC(12,2) DEFAULT 0 NOT NULL,
        public string DLV_SAFE_TEL_NO { get; set; } = string.Empty;            //DLV_SAFE_TEL_NO          VARCHAR(15), 
        public string DLV_EXPIRE_TIME { get; set; } = string.Empty;            //DLV_EXPIRE_TIME          VARCHAR(14), 
        public string EXTERN_GUEST_FLAG { get; set; } = "0";          //EXTERN_GUEST_FLAG        VARCHAR(1) DEFAULT '0', 
        public string DCC_EX_RATE_CODE { get; set; } = string.Empty;           //DCC_EX_RATE_CODE         VARCHAR(1), 
        public string DCC_RCV_TEXT { get; set; } = string.Empty;               //DCC_RCV_TEXT             VARCHAR(100), 
        public string SP_PAY_AMT { get; set; } = "0";                 //SP_PAY_AMT               NUMERIC(12,2) DEFAULT 0 NOT NULL, 
        public string HOOK_ORDER_CHANNEL_TYPE { get; set; } = "";    //HOOK_ORDER_CHANNEL_TYPE  VARCHAR(30) DEFAULT '', 
        public string DEPOSIT_AMT { get; set; } = "0";                //DEPOSIT_AMT              NUMERIC(12,2) DEFAULT 0 NOT NULL
    } 
}
